version: "3.2"

services:
  web:
    image: gbenson/mediawiki
    links:
      - database
    ports:
      - 8888:80
    volumes:
      - ./staging:/var/www/html
      - images:/var/www/html/images

  database:
    image: mariadb
    hostname: mysql.gbenson.net
    env_file: database/settings.env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - database:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

volumes:
  database:
  images:
