#!/bin/sh

set -exu

if [ $# != 0 ]; then
  echo 1>&2 "usage: $0"
  exit 1
fi

clean_builddir ()
{
  builddir="$1"
  for i in "$builddir"/.[^.]* "$builddir"/*; do
    case "$i" in
      "$builddir"/.git*) ;;
      "$builddir"/.htaccess) ;;
      "$builddir"/LocalSettings*.php) ;;
      *) rm -rf "$i"
    esac
  done
}

topdir=$(cd $(dirname "$0") && pwd)
srcdir="$topdir/source"
builddir="$topdir/staging"

# Extract the document root from the container image.
srcimg=gbenson/mediawiki
docker pull "$srcimg"
clean_builddir "$builddir"
docker run --rm -i "$srcimg" tar -cf - . | tar -xf - -C "$builddir"
chmod og+w "$builddir/cache"
